version: "3.9"

services:
  phoenix:
    build: .
    container_name: wabanex-app
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: wabanex-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wabanex_dev
    ports:
      - "5432:5432"
    restart: always