version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: wabanex-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wabanex_dev
    ports:
      - "5432:5432"